name: Cross-Browser Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run tests
        run: |
          PW_BROWSER=${{ matrix.browser }} pytest tests --alluredir=allure-results --browser=${{ matrix.browser }}
      
      - name: Add environment info to Allure results
        run: |
          echo "Browser=${{ matrix.browser }}" > allure-results/environment.properties
          
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results

  report-merge:
    name: Merge & Deploy Allure Report
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          path: merged-results

      - name: Merge Allure Results
        run: |
          mkdir -p final-results
          find merged-results -type f ! -name "environment.properties" -exec cp {} final-results/ \;
          echo "" > final-results/environment.properties
          i=1
          for envfile in $(find merged-results -name "environment.properties"); do
            while IFS= read -r line; do
              key=$(echo "$line" | cut -d '=' -f 1)
              value=$(echo "$line" | cut -d '=' -f 2-)
              echo "${key}_${i}=${value}" >> final-results/environment.properties
            done < "$envfile"
            i=$((i+1))
          done

      - name: Generate Allure HTML Report
        run: |
          pip install allure-pytest
          npm install -g allure-commandline --save-dev
          echo "REPORT_TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
          allure generate final-results --clean -o allure-report-${{ env.REPORT_TIMESTAMP }}

      - name: Prepare gh-pages branch with index.html
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages-temp
          cd gh-pages-temp
          cp -r ../allure-report-${{ env.REPORT_TIMESTAMP }} ./
          echo '<html><head><title>Allure Reports Index</title></head><body><h1>Allure Reports</h1><ul>' > index.html
          for dir in allure-report-*; do
            echo "<li><a href=\"$dir/\">$dir</a></li>" >> index.html
          done
          echo '</ul></body></html>' >> index.html
          git add .
          git commit -m "Add Allure report ${{ env.REPORT_TIMESTAMP }} and update index"
          git push origin gh-pages

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "✅ TestPilot-AI CI tests completed. View the Allure report here: https://phoenix2rise.github.io/TestPilot-AI/index.html"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
