name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run tests
      run: |
        pytest --browser ${{ matrix.browser }} --html=reports/report-${{ matrix.browser }}.html

    - name: Upload Allure results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results

    - name: Notify Slack
      if: failure()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": ":x: *TestPilot-AI* GitHub CI failed on `${{ matrix.browser }}`! Check the report."
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
