name: Cross-Browser Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run tests
        run: |
          PW_BROWSER=${{ matrix.browser }} pytest tests --alluredir=allure-results

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results

  report-merge:
    name: Merge & Upload Allure Report
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          path: merged-results

      - name: Merge Allure Results
        run: |
          mkdir combined-results
          cp -r merged-results/*/ combined-results/

      - name: Generate Allure HTML Report
        run: |
          pip install allure-pytest
          npm install -g allure-commandline --save-dev
          allure generate combined-results --clean -o allure-report

      - name: Upload Final HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
         payload: |
          {
            "text": "✅ CI/CD pipeline succeeded for ${{ github.repository }} on branch ${{ github.ref_name }}"
          }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}